/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UTS1;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fysl
 */

public class Beli extends javax.swing.JFrame {

    /**
     * Creates new form seblak
     */
    
    public Beli() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        ayam = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        hrg4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        kerupuk = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        hrg3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        hrg2 = new javax.swing.JLabel();
        pentol = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        hrg1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sosis = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        hrg5 = new javax.swing.JLabel();
        udang = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        hrg6 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mie = new javax.swing.JCheckBox();
        jPanel9 = new javax.swing.JPanel();
        hrg7 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bakpao = new javax.swing.JCheckBox();
        jPanel10 = new javax.swing.JPanel();
        hrg8 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        makroni = new javax.swing.JCheckBox();
        jPanel11 = new javax.swing.JPanel();
        hrg9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        telur = new javax.swing.JCheckBox();
        jPanel13 = new javax.swing.JPanel();
        hrg11 = new javax.swing.JLabel();
        sawi = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        hrg12 = new javax.swing.JLabel();
        tahu = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        hrg13 = new javax.swing.JLabel();
        puyuh = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        judl5 = new javax.swing.JLabel();
        beli = new javax.swing.JButton();
        nama = new javax.swing.JTextField();
        judl3 = new javax.swing.JLabel();
        varian = new javax.swing.JComboBox<>();
        judl6 = new javax.swing.JLabel();
        level = new javax.swing.JComboBox<>();
        batal = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        hasil = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        btntotal = new javax.swing.JButton();
        hasiltotal = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        judl4 = new javax.swing.JLabel();
        potongan3 = new javax.swing.JLabel();
        potongan1 = new javax.swing.JLabel();
        garisapi = new javax.swing.JLabel();
        garisapi1 = new javax.swing.JLabel();
        potongan4 = new javax.swing.JLabel();
        apikiri = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        bantuan = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(102, 0, 0));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(128, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(152, 43, 28));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(128, 43, 28));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(51, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ayam.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        ayam.setForeground(new java.awt.Color(242, 232, 198));
        ayam.setText("Irisan Ayam");
        ayam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayamActionPerformed(evt);
            }
        });
        jPanel3.add(ayam, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTS/gambaruts/irisan.png"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 60));

        hrg4.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        hrg4.setForeground(new java.awt.Color(242, 232, 198));
        hrg4.setText("Rp. 2500");
        jPanel3.add(hrg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 130, 140));

        jPanel4.setBackground(new java.awt.Color(128, 43, 28));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(51, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kerupuk.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        kerupuk.setForeground(new java.awt.Color(242, 232, 198));
        kerupuk.setText("Kerupuk");
        kerupuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kerupukActionPerformed(evt);
            }
        });
        jPanel4.add(kerupuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTS/gambaruts/krupuk.png"))); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 60));

        hrg3.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        hrg3.setForeground(new java.awt.Color(242, 232, 198));
        hrg3.setText("Rp. 800");
        jPanel4.add(hrg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 130, 140));

        jPanel5.setBackground(new java.awt.Color(128, 43, 28));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(51, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTS/gambaruts/bakso.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 60));

        hrg2.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        hrg2.setForeground(new java.awt.Color(242, 232, 198));
        hrg2.setText("Rp. 1000");
        jPanel5.add(hrg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        pentol.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        pentol.setForeground(new java.awt.Color(242, 232, 198));
        pentol.setText("Pentol Bakso");
        pentol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pentolActionPerformed(evt);
            }
        });
        jPanel5.add(pentol, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 130, 140));

        jPanel6.setBackground(new java.awt.Color(128, 43, 28));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(51, 0, 0)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hrg1.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        hrg1.setForeground(new java.awt.Color(242, 232, 198));
        hrg1.setText("Rp. 1000");
        jPanel6.add(hrg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTS/gambaruts/sosis.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 60));

        sosis.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        sosis.setForeground(new java.awt.Color(242, 232, 198));
        sosis.setText("Sosis");
        sosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sosisActionPerformed(evt);
            }
        });
        jPanel6.add(sosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 130, 140));

        jPanel7.setBackground(new java.awt.Color(128, 43, 28));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(51, 0, 0)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hrg5.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        hrg5.setForeground(new java.awt.Color(242, 232, 198));
        hrg5.setText("Rp. 1000");
        jPanel7.add(hrg5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        udang.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        udang.setForeground(new java.awt.Color(242, 232, 198));
        udang.setText("Kerupuk Udang");
        udang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                udangActionPerformed(evt);
            }
        });
        jPanel7.add(udang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTS/gambaruts/krupuk bash.png"))); // NOI18N
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 60));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 130, 140));

        jPanel8.setBackground(new java.awt.Color(128, 43, 28));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(51, 0, 0)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hrg6.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        hrg6.setForeground(new java.awt.Color(242, 232, 198));
        hrg6.setText("Rp. 1500");
        jPanel8.add(hrg6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTS/gambaruts/mie.png"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 60));

        mie.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        mie.setForeground(new java.awt.Color(242, 232, 198));
        mie.setText("Mie");
        mie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mieActionPerformed(evt);
            }
        });
        jPanel8.add(mie, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, 130, 140));

        jPanel9.setBackground(new java.awt.Color(128, 43, 28));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(51, 0, 0)));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hrg7.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        hrg7.setForeground(new java.awt.Color(242, 232, 198));
        hrg7.setText("Rp. 2000");
        jPanel9.add(hrg7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTS/gambaruts/bakpao.png"))); // NOI18N
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 60));

        bakpao.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        bakpao.setForeground(new java.awt.Color(242, 232, 198));
        bakpao.setText("Bakpao");
        bakpao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bakpaoActionPerformed(evt);
            }
        });
        jPanel9.add(bakpao, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, 130, 140));

        jPanel10.setBackground(new java.awt.Color(128, 43, 28));
        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(51, 0, 0)));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hrg8.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        hrg8.setForeground(new java.awt.Color(242, 232, 198));
        hrg8.setText("Rp. 800");
        jPanel10.add(hrg8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTS/gambaruts/makroni.png"))); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel10.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 60));

        makroni.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        makroni.setForeground(new java.awt.Color(242, 232, 198));
        makroni.setText("Makroni");
        makroni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makroniActionPerformed(evt);
            }
        });
        jPanel10.add(makroni, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 130, 140));

        jPanel11.setBackground(new java.awt.Color(128, 43, 28));
        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(51, 0, 0)));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hrg9.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        hrg9.setForeground(new java.awt.Color(242, 232, 198));
        hrg9.setText("Rp. 2500");
        jPanel11.add(hrg9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTS/gambaruts/telur.png"))); // NOI18N
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel11.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 60));

        telur.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        telur.setForeground(new java.awt.Color(242, 232, 198));
        telur.setText("Telur");
        telur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telurActionPerformed(evt);
            }
        });
        jPanel11.add(telur, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 130, 140));

        jPanel13.setBackground(new java.awt.Color(128, 43, 28));
        jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(51, 0, 0)));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hrg11.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        hrg11.setForeground(new java.awt.Color(242, 232, 198));
        hrg11.setText("Rp. 800");
        jPanel13.add(hrg11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        sawi.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        sawi.setForeground(new java.awt.Color(242, 232, 198));
        sawi.setText("Sawi");
        sawi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sawiActionPerformed(evt);
            }
        });
        jPanel13.add(sawi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTS/gambaruts/sawi.png"))); // NOI18N
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel13.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 60));

        jPanel2.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 130, 140));

        jPanel14.setBackground(new java.awt.Color(128, 43, 28));
        jPanel14.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(51, 0, 0)));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hrg12.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        hrg12.setForeground(new java.awt.Color(242, 232, 198));
        hrg12.setText("Rp. 1300");
        jPanel14.add(hrg12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        tahu.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        tahu.setForeground(new java.awt.Color(242, 232, 198));
        tahu.setText("Tahu");
        tahu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahuActionPerformed(evt);
            }
        });
        jPanel14.add(tahu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTS/gambaruts/tahu.png"))); // NOI18N
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel14.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 60));

        jPanel2.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 130, 140));

        jPanel15.setBackground(new java.awt.Color(128, 43, 28));
        jPanel15.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(51, 0, 0)));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hrg13.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        hrg13.setForeground(new java.awt.Color(242, 232, 198));
        hrg13.setText("Rp. 900");
        jPanel15.add(hrg13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        puyuh.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        puyuh.setForeground(new java.awt.Color(242, 232, 198));
        puyuh.setText("Telur Puyuh");
        puyuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puyuhActionPerformed(evt);
            }
        });
        jPanel15.add(puyuh, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTS/gambaruts/puyuh.png"))); // NOI18N
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel15.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 60));

        jPanel2.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 130, 140));

        judl5.setFont(new java.awt.Font("Ravie", 0, 20)); // NOI18N
        judl5.setForeground(new java.awt.Color(242, 232, 198));
        judl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judl5.setText("Masukkan Nama");
        jPanel2.add(judl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 230, 40));

        beli.setBackground(new java.awt.Color(218, 212, 181));
        beli.setFont(new java.awt.Font("Ravie", 0, 22)); // NOI18N
        beli.setForeground(new java.awt.Color(51, 0, 0));
        beli.setText("Beli");
        beli.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliActionPerformed(evt);
            }
        });
        jPanel2.add(beli, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 110, 40));

        nama.setBackground(new java.awt.Color(204, 204, 204));
        nama.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        nama.setForeground(new java.awt.Color(51, 51, 51));
        nama.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        jPanel2.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 230, 40));

        judl3.setFont(new java.awt.Font("Ravie", 0, 20)); // NOI18N
        judl3.setForeground(new java.awt.Color(242, 232, 198));
        judl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judl3.setText("Varian");
        jPanel2.add(judl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 250, 30));

        varian.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        varian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-", "Kuah", "Kering" }));
        jPanel2.add(varian, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 190, 40));

        judl6.setFont(new java.awt.Font("Ravie", 0, 20)); // NOI18N
        judl6.setForeground(new java.awt.Color(242, 232, 198));
        judl6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judl6.setText("Pilih Level");
        jPanel2.add(judl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 250, 40));

        level.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", " " }));
        jPanel2.add(level, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 190, 40));

        batal.setBackground(new java.awt.Color(218, 212, 181));
        batal.setFont(new java.awt.Font("Ravie", 0, 22)); // NOI18N
        batal.setForeground(new java.awt.Color(51, 0, 0));
        batal.setText("Batal");
        batal.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        jPanel2.add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, -1, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 810, 480));

        jPanel12.setBackground(new java.awt.Color(152, 43, 28));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Level", "Varian", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel.setEnabled(false);
        jScrollPane2.setViewportView(tabel);
        if (tabel.getColumnModel().getColumnCount() > 0) {
            tabel.getColumnModel().getColumn(0).setHeaderValue("Nama");
            tabel.getColumnModel().getColumn(1).setHeaderValue("Level");
            tabel.getColumnModel().getColumn(2).setHeaderValue("Varian");
            tabel.getColumnModel().getColumn(3).setHeaderValue("Harga");
        }

        jPanel12.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 120));

        hasil.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        hasil.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel12.add(hasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 170, 50));

        jLabel16.setFont(new java.awt.Font("Ravie", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(242, 232, 198));
        jLabel16.setText("Harga");
        jPanel12.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        area.setColumns(20);
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        jPanel12.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 300, 140));

        btntotal.setBackground(new java.awt.Color(218, 212, 181));
        btntotal.setFont(new java.awt.Font("Ravie", 0, 22)); // NOI18N
        btntotal.setForeground(new java.awt.Color(51, 0, 0));
        btntotal.setText("Total");
        btntotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntotalActionPerformed(evt);
            }
        });
        jPanel12.add(btntotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, 40));

        hasiltotal.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        hasiltotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel12.add(hasiltotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 280, 50));

        jLabel17.setFont(new java.awt.Font("Ravie", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(242, 232, 198));
        jLabel17.setText("Toping Varian");
        jPanel12.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 110, 320, 480));

        back.setBackground(new java.awt.Color(218, 212, 181));
        back.setFont(new java.awt.Font("Ravie", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(51, 0, 0));
        back.setText("Kembali");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 60, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTS/gambaruts/seblak.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        judl4.setFont(new java.awt.Font("Ravie", 1, 36)); // NOI18N
        judl4.setForeground(new java.awt.Color(242, 232, 198));
        judl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judl4.setText("Pilih Toping Favorit");
        jPanel1.add(judl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 530, 50));

        potongan3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTS/gambaruts/SEBLAK PRASMANAN (2 x 1 inci).png"))); // NOI18N
        jPanel1.add(potongan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 500, 227, -1));

        potongan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTS/gambaruts/SEBLAK PRASMANAN (2 x 1 inci).png"))); // NOI18N
        jPanel1.add(potongan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, 227, -1));

        garisapi.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        garisapi.setForeground(new java.awt.Color(255, 255, 255));
        garisapi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTS/gambaruts/SEBLAK PRASMANAN.png"))); // NOI18N
        jPanel1.add(garisapi, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 750, 170));

        garisapi1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        garisapi1.setForeground(new java.awt.Color(255, 255, 255));
        garisapi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTS/gambaruts/SEBLAK PRASMANAN.png"))); // NOI18N
        jPanel1.add(garisapi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, 0, 750, 170));

        potongan4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTS/gambaruts/SEBLAK PRASMANAN (2 x 1 inci).png"))); // NOI18N
        jPanel1.add(potongan4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, 40, 227, -1));

        apikiri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTS/gambaruts/SEBLAK PRASMANAN (1).png"))); // NOI18N
        jPanel1.add(apikiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 440, 450, 340));

        jMenu1.setText("Beranda");

        jMenuItem1.setText("Menu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        bantuan.setText("Informasi");
        bantuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bantuanActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Informasi Pesanan");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        bantuan.add(jMenuItem3);

        jMenuBar1.add(bantuan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1193, 650));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sosisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sosisActionPerformed

    private void ayamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ayamActionPerformed

    private void pentolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pentolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pentolActionPerformed

    private void kerupukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kerupukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kerupukActionPerformed

    private void udangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_udangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_udangActionPerformed

    private void mieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mieActionPerformed

    private void bakpaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bakpaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bakpaoActionPerformed

    private void makroniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makroniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_makroniActionPerformed

    private void telurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telurActionPerformed

    private void sawiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sawiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sawiActionPerformed

    private void tahuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tahuActionPerformed

    private void puyuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puyuhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puyuhActionPerformed
  
    
    private void beliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliActionPerformed
        // TODO add your handling code here:
        
        //validasi input
        String nm=nama.getText();
        if (nm.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nama harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        String selectedItem = (String) varian.getSelectedItem();
        if("-Pilih-".equals(selectedItem)){
                JOptionPane.showMessageDialog(this, "Harap Pilih Varian", "Error", JOptionPane.ERROR_MESSAGE);
                return;
        }
        
        
        
        //total
        int total=0;
        StringBuilder x= new StringBuilder();
        
        //kerupuk
        if(kerupuk.isSelected()){
            total +=800;
            x.append("Kerupuk \t\t = Rp.800\n");
        }
        //irisan
        if(ayam.isSelected()){
            total +=2500;
            x.append("Irisan Ayam \t\t = Rp.2500\n");
        }
        //pentol
        if(pentol.isSelected()){
            total +=1000;
            x.append("Pentol Bakso \t\t = Rp.1000\n");
        }
        //sosis
        if(sosis.isSelected()){
            total +=1000;
            x.append("Sosis \t\t = Rp.1000\n");
        }
        //bakpao
        if(bakpao.isSelected()){
            total +=2000;
            x.append("Bakpao \t\t = Rp.2000\n");
        }
        //mie
        if(mie.isSelected()){
            total +=1500;
            x.append("Mie \t\t = Rp.1500\n");
        }
        //makroni
        if(makroni.isSelected()){
            total +=800;
            x.append("Makroni \t\t = Rp.800\n");
        }
        //telur
        if(telur.isSelected()){
            total +=2500;
            x.append("Telur \t\t = Rp.2500\n");
        }
        //sawi
         if(sawi.isSelected()){
            total +=800;
            x.append("Sawi \t\t = Rp.800\n");
        }
         //tahu
          if(tahu.isSelected()){
            total +=1300;
            x.append("Tahu \t\t = Rp.1300\n");
        }
         //puyuh
          if(puyuh.isSelected()){
            total +=900;
            x.append("Telur Puyuh \t\t = Rp.900\n");
        }
         //udang
          if(udang.isSelected()){
            total +=1000;
            x.append("Kerupuk Udang \t = Rp.1000\n");
        }
        
        area.setText(""+x +"-------------------------------------------------------------- +\n" + "Total \t\t = Rp."+total);
        
        //menampilkan total
        hasil.setText("Rp."+total);
        
        //tabel
        DefaultTableModel model=(DefaultTableModel)tabel.getModel();
        model.addRow(new Object[]{
            nama.getText(),
            level.getSelectedItem(),
            varian.getSelectedItem(),
            hasil.getText()
        });
        
       
    }//GEN-LAST:event_beliActionPerformed

    private void bantuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bantuanActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_bantuanActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
         info i=new info();
        i.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        menu s=new menu();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_namaActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        // TODO add your handling code here:
        //hapus centang pada chexbox
        kerupuk.setSelected(false);
        ayam.setSelected(false);
        pentol.setSelected(false);
        sosis.setSelected(false);
        bakpao.setSelected(false);
        mie.setSelected(false);
        makroni.setSelected(false);
        telur.setSelected(false);
        sawi.setSelected(false);
        tahu.setSelected(false);
        puyuh.setSelected(false);
        udang.setSelected(false);
        
        //hapus pada textfield
        nama.setText("");
        hasil.setText("");
        area.setText("");
        
        //hapus combo box
        level.setSelectedIndex(0);
        varian.setSelectedIndex(0);
    }//GEN-LAST:event_batalActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        menu s=new menu();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void btntotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntotalActionPerformed
        // TODO add your handling code here:
        int totalKeseluruhan = 0; // untuk menyimpan total semua harga
        DefaultTableModel model = (DefaultTableModel)tabel.getModel();
        for (int i = 0; i < tabel.getRowCount(); i++) {
        String hargaStr = tabel.getValueAt(i, 3).toString(); // Ambil nilai dari kolom ke-3 yaitu harga
        
        // Menghapus "Rp." jika ada dan konversi ke integer
        int harga = Integer.parseInt(hargaStr.replace("Rp.", ""));
        totalKeseluruhan += harga; // Menambahkan harga ke total
        }
        hasiltotal.setText("Rp."+totalKeseluruhan);
        
    }//GEN-LAST:event_btntotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Beli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Beli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Beli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Beli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Beli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apikiri;
    private javax.swing.JTextArea area;
    private javax.swing.JCheckBox ayam;
    private javax.swing.JButton back;
    private javax.swing.JCheckBox bakpao;
    private javax.swing.JMenu bantuan;
    private javax.swing.JButton batal;
    private javax.swing.JButton beli;
    private javax.swing.JButton btntotal;
    private javax.swing.JLabel garisapi;
    private javax.swing.JLabel garisapi1;
    private javax.swing.JTextField hasil;
    private javax.swing.JTextField hasiltotal;
    private javax.swing.JLabel hrg1;
    private javax.swing.JLabel hrg11;
    private javax.swing.JLabel hrg12;
    private javax.swing.JLabel hrg13;
    private javax.swing.JLabel hrg2;
    private javax.swing.JLabel hrg3;
    private javax.swing.JLabel hrg4;
    private javax.swing.JLabel hrg5;
    private javax.swing.JLabel hrg6;
    private javax.swing.JLabel hrg7;
    private javax.swing.JLabel hrg8;
    private javax.swing.JLabel hrg9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel judl3;
    private javax.swing.JLabel judl4;
    private javax.swing.JLabel judl5;
    private javax.swing.JLabel judl6;
    private javax.swing.JCheckBox kerupuk;
    private javax.swing.JComboBox<String> level;
    private javax.swing.JCheckBox makroni;
    private javax.swing.JCheckBox mie;
    public javax.swing.JTextField nama;
    private javax.swing.JCheckBox pentol;
    private javax.swing.JLabel potongan1;
    private javax.swing.JLabel potongan3;
    private javax.swing.JLabel potongan4;
    private javax.swing.JCheckBox puyuh;
    private javax.swing.JCheckBox sawi;
    private javax.swing.JCheckBox sosis;
    private javax.swing.JTable tabel;
    private javax.swing.JCheckBox tahu;
    private javax.swing.JCheckBox telur;
    private javax.swing.JCheckBox udang;
    private javax.swing.JComboBox<String> varian;
    // End of variables declaration//GEN-END:variables
}
