/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UAS;

import UTS.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fysl
 */

public class Daftar extends Beli {

    /**
     * Creates new form seblak
     */
    Koneksi k=new Koneksi();
    
    public Daftar() {
        initComponents();
        
        
        //Status
        k.koneksiData();
        this.status.setText(k.statuskoneksi);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        judl15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        status = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        judl4 = new javax.swing.JLabel();
        potongan3 = new javax.swing.JLabel();
        garisapi1 = new javax.swing.JLabel();
        potongan4 = new javax.swing.JLabel();
        apikiri = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        judl17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Back = new javax.swing.JButton();
        ubah1 = new javax.swing.JButton();
        garisapi = new javax.swing.JLabel();
        potongan1 = new javax.swing.JLabel();
        hapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(102, 0, 0));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(128, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(152, 43, 28));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judl15.setFont(new java.awt.Font("Ravie", 0, 20)); // NOI18N
        judl15.setForeground(new java.awt.Color(242, 232, 198));
        judl15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judl15.setText("Pembelian");
        jPanel2.add(judl15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 160, 40));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama", "Level", "Varian", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 550, 210));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 570, 480));

        status.setBackground(new java.awt.Color(204, 204, 204));
        status.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        status.setForeground(new java.awt.Color(51, 51, 51));
        status.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        jPanel1.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 600, 680, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTS/gambaruts/seblak.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        judl4.setFont(new java.awt.Font("Ravie", 1, 36)); // NOI18N
        judl4.setForeground(new java.awt.Color(242, 232, 198));
        judl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judl4.setText("Daftar Pesanan");
        jPanel1.add(judl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 530, 50));

        potongan3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTS/gambaruts/SEBLAK PRASMANAN (2 x 1 inci).png"))); // NOI18N
        jPanel1.add(potongan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 500, 227, -1));

        garisapi1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        garisapi1.setForeground(new java.awt.Color(255, 255, 255));
        garisapi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTS/gambaruts/SEBLAK PRASMANAN.png"))); // NOI18N
        jPanel1.add(garisapi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, 0, 750, 170));

        potongan4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTS/gambaruts/SEBLAK PRASMANAN (2 x 1 inci).png"))); // NOI18N
        jPanel1.add(potongan4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, 40, 227, -1));

        apikiri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTS/gambaruts/SEBLAK PRASMANAN (1).png"))); // NOI18N
        jPanel1.add(apikiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 520, 450, 190));

        jPanel7.setBackground(new java.awt.Color(152, 43, 28));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judl17.setFont(new java.awt.Font("Ravie", 0, 20)); // NOI18N
        judl17.setForeground(new java.awt.Color(242, 232, 198));
        judl17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judl17.setText("Pemesanan");
        jPanel7.add(judl17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 160, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama", "Jenis", "Jumlah", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 550, 210));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 570, 480));

        Back.setBackground(new java.awt.Color(218, 212, 181));
        Back.setFont(new java.awt.Font("Ravie", 0, 18)); // NOI18N
        Back.setForeground(new java.awt.Color(51, 0, 0));
        Back.setText("Kembali");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel1.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 60, 140, -1));

        ubah1.setBackground(new java.awt.Color(218, 212, 181));
        ubah1.setFont(new java.awt.Font("Ravie", 0, 18)); // NOI18N
        ubah1.setForeground(new java.awt.Color(51, 0, 0));
        ubah1.setText("Ubah");
        ubah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubah1ActionPerformed(evt);
            }
        });
        jPanel1.add(ubah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 600, 110, -1));

        garisapi.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        garisapi.setForeground(new java.awt.Color(255, 255, 255));
        garisapi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTS/gambaruts/SEBLAK PRASMANAN.png"))); // NOI18N
        jPanel1.add(garisapi, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 750, 170));

        potongan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTS/gambaruts/SEBLAK PRASMANAN (2 x 1 inci).png"))); // NOI18N
        jPanel1.add(potongan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, 227, -1));

        hapus.setBackground(new java.awt.Color(218, 212, 181));
        hapus.setFont(new java.awt.Font("Ravie", 0, 18)); // NOI18N
        hapus.setForeground(new java.awt.Color(51, 0, 0));
        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel1.add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 600, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        menu s=new menu();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void ubah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubah1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubah1ActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hapusActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Daftar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel apikiri;
    private javax.swing.JLabel garisapi;
    private javax.swing.JLabel garisapi1;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel judl15;
    private javax.swing.JLabel judl17;
    private javax.swing.JLabel judl4;
    private javax.swing.JLabel potongan1;
    private javax.swing.JLabel potongan3;
    private javax.swing.JLabel potongan4;
    public javax.swing.JTextField status;
    private javax.swing.JButton ubah1;
    // End of variables declaration//GEN-END:variables
}
