/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UAS;

import UTS.*;

/**
 *
 * @author Fysl
 */

public class info extends Beli {

    /**
     * Creates new form seblak
     */
    
    public info() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        judl4 = new javax.swing.JLabel();
        potongan3 = new javax.swing.JLabel();
        potongan1 = new javax.swing.JLabel();
        garisapi = new javax.swing.JLabel();
        garisapi1 = new javax.swing.JLabel();
        garisapi2 = new javax.swing.JLabel();
        potongan4 = new javax.swing.JLabel();
        apikiri = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(102, 0, 0));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(128, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 204,50));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Date : 15/12/2024");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 460, -1, -1));

        jLabel6.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("@seblakgenirawit");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, -1, 40));

        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Seblak Geni Rawit");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTS/gambaruts/seblak.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, -1, -1));

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(107, 43, 27));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Palatino Linotype", 0, 13)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("Seblak Geni Rawit adalah hidangan spesial yang menggoda lidah dengan cita rasa pedas membara. Terinspirasi dari semangat api yang membakar, seblak ini dibuat khusus untuk pecinta makanan pedas ekstrem.\nDengan perpaduan kerupuk basah, bumbu khas rempah Nusantara, dan cabe rawit pilihan, Seblak Geni Rawit menghadirkan sensasi pedas yang bikin nagih!!!\n");
        jScrollPane2.setViewportView(jTextArea2);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 460, 150));

        jPanel3.setBackground(new java.awt.Color(218, 212, 181));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTS/gambaruts/aku.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), java.awt.Color.white));
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 150, 310));

        jLabel4.setFont(new java.awt.Font("Ravie", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 0));
        jLabel4.setText("2355201027");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Ravie", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 0));
        jLabel7.setText("Faisal Eka Nur I");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 230, 390));

        jLabel2.setFont(new java.awt.Font("Ravie", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 0));
        jLabel2.setText("By :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 860, 20));

        jLabel8.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Alamat :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTS/gambaruts/tt.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 60, 50));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTS/gambaruts/ig.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 60, 50));

        jLabel10.setFont(new java.awt.Font("Palatino Linotype", 2, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Jln. Singo Kromo, Rejoso, Binangun");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel13.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("@seblak.geni.rawit");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, -1, 40));

        jLabel14.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("No tlp :");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jLabel15.setFont(new java.awt.Font("Palatino Linotype", 2, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("089736412221");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 860, 480));

        back.setBackground(new java.awt.Color(218, 212, 181));
        back.setFont(new java.awt.Font("Ravie", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(51, 0, 0));
        back.setText("Kembali");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, -1, -1));

        judl4.setFont(new java.awt.Font("Ravie", 1, 36)); // NOI18N
        judl4.setForeground(new java.awt.Color(242, 232, 198));
        judl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judl4.setText("Informasi");
        jPanel1.add(judl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 530, 50));

        potongan3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTS/gambaruts/SEBLAK PRASMANAN (2 x 1 inci).png"))); // NOI18N
        jPanel1.add(potongan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 330, 227, -1));

        potongan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTS/gambaruts/SEBLAK PRASMANAN (2 x 1 inci).png"))); // NOI18N
        jPanel1.add(potongan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 227, -1));

        garisapi.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        garisapi.setForeground(new java.awt.Color(255, 255, 255));
        garisapi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTS/gambaruts/SEBLAK PRASMANAN.png"))); // NOI18N
        jPanel1.add(garisapi, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 750, 170));

        garisapi1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        garisapi1.setForeground(new java.awt.Color(255, 255, 255));
        garisapi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTS/gambaruts/SEBLAK PRASMANAN.png"))); // NOI18N
        jPanel1.add(garisapi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, 0, 750, 170));

        garisapi2.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        garisapi2.setForeground(new java.awt.Color(255, 255, 255));
        garisapi2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fysl\\Downloads\\SEBLAK PRASMANAN.png")); // NOI18N
        jPanel1.add(garisapi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, 0, 750, 170));

        potongan4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTS/gambaruts/SEBLAK PRASMANAN (2 x 1 inci).png"))); // NOI18N
        jPanel1.add(potongan4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, 30, 227, -1));

        apikiri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTS/gambaruts/SEBLAK PRASMANAN (1).png"))); // NOI18N
        jPanel1.add(apikiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(-250, 480, 450, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(930, 650));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        menu s=new menu();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apikiri;
    private javax.swing.JButton back;
    private javax.swing.JLabel garisapi;
    private javax.swing.JLabel garisapi1;
    private javax.swing.JLabel garisapi2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel judl4;
    private javax.swing.JLabel potongan1;
    private javax.swing.JLabel potongan3;
    private javax.swing.JLabel potongan4;
    // End of variables declaration//GEN-END:variables
}
