/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugasJDBC;


import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author Fysl
 */
public class MahasiswaILKOM extends javax.swing.JFrame {

    /**
     * Creates new form DataMhsILKOM
     */
    //memanggil kelas
    Koneksi Konek= new Koneksi();
    Query qw=new Query();
    
    public MahasiswaILKOM() {
        initComponents();
        
        //Judul
        this.setTitle("Data ILKOM");
        this.setLocationRelativeTo(this);
        
        //koneksi
        Konek.koneksiData();
        this.KONEKSI.setText(Konek.statuskoneksi);
        
        //tabel
        //qw.load();
      loadtabel();
    }
    
    public void loadtabel() {
        String load = "SELECT * FROM identitas";
        Konek.koneksiData();
        try {
            PreparedStatement st = Konek.conn.prepareStatement(load);
            ResultSet rs = st.executeQuery();
            TABEL.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception ex) {
              System.out.println("Gagal coyyy");
        }

    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nim = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        simpan1 = new javax.swing.JButton();
        nama = new javax.swing.JTextField();
        JK = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABEL = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        riset = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        KONEKSI = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        nama1 = new javax.swing.JTextField();
        nim1 = new javax.swing.JTextField();
        alamat1 = new javax.swing.JTextField();
        JK1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(22, 66, 60));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Imprint MT Shadow", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NIM");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Imprint MT Shadow", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Jenis Kelamin");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        nim.setBackground(new java.awt.Color(255, 255, 255));
        nim.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        nim.setForeground(new java.awt.Color(22, 66, 60));
        nim.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimActionPerformed(evt);
            }
        });
        jPanel1.add(nim, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 250, -1));

        jLabel8.setFont(new java.awt.Font("Imprint MT Shadow", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Alamat Mahasiswa");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        alamat.setBackground(new java.awt.Color(255, 255, 255));
        alamat.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        alamat.setForeground(new java.awt.Color(22, 66, 60));
        alamat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 250, 50));

        jLabel9.setFont(new java.awt.Font("Imprint MT Shadow", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Masukkan Nama");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        simpan1.setBackground(new java.awt.Color(196, 218, 210));
        simpan1.setFont(new java.awt.Font("Broadway", 0, 18)); // NOI18N
        simpan1.setForeground(new java.awt.Color(22, 66, 60));
        simpan1.setText("SIMPAN");
        simpan1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        simpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan1ActionPerformed(evt);
            }
        });
        jPanel1.add(simpan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 287, 160, 40));

        nama.setBackground(new java.awt.Color(255, 255, 255));
        nama.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        nama.setForeground(new java.awt.Color(22, 66, 60));
        nama.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        jPanel1.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 250, -1));

        JK.setBackground(new java.awt.Color(106, 156, 137));
        JK.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        JK.setForeground(new java.awt.Color(0, 0, 0));
        JK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));
        jPanel1.add(JK, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 170, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 300, 340));

        jPanel2.setBackground(new java.awt.Color(106, 156, 137));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("DATA MAHASISWA");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 360, 30));

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(196, 218, 210));
        jLabel3.setText("Universitas Nahdlatul Ulama Blitar");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 510, 30));
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        jLabel17.setFont(new java.awt.Font("Cooper Black", 0, 52)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(233, 239, 236));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("ILKOM");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 70));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 100));

        jPanel3.setBackground(new java.awt.Color(22, 66, 60));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TABEL.setAutoCreateRowSorter(true);
        TABEL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "NIM", "Alamat", "Jenis Kelamin"
            }
        ));
        TABEL.setGridColor(new java.awt.Color(255, 255, 255));
        TABEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABELMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TABEL);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 220));

        jLabel4.setFont(new java.awt.Font("Imprint MT Shadow", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Data Mahasiswa Ilmu Komputer");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 280, -1));

        riset.setBackground(new java.awt.Color(196, 218, 210));
        riset.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        riset.setForeground(new java.awt.Color(22, 66, 60));
        riset.setText("Riset");
        riset.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102)));
        riset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                risetActionPerformed(evt);
            }
        });
        jPanel3.add(riset, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 50, 30));

        hapus.setBackground(new java.awt.Color(196, 218, 210));
        hapus.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        hapus.setForeground(new java.awt.Color(22, 66, 60));
        hapus.setText("Hapus");
        hapus.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel3.add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 60, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 490, 340));

        jPanel4.setBackground(new java.awt.Color(106, 156, 137));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        KONEKSI.setEditable(false);
        KONEKSI.setBackground(new java.awt.Color(255, 255, 255));
        KONEKSI.setForeground(new java.awt.Color(22, 66, 60));
        KONEKSI.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        KONEKSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KONEKSIActionPerformed(evt);
            }
        });
        jPanel4.add(KONEKSI, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 490, -1));

        jLabel12.setBackground(new java.awt.Color(22, 66, 60));
        jLabel12.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(22, 66, 60));
        jLabel12.setText("Status Koneksi JDBC");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 150, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 800, 40));

        jPanel5.setBackground(new java.awt.Color(22, 66, 60));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Imprint MT Shadow", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nama");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel16.setFont(new java.awt.Font("Imprint MT Shadow", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Jenis Kelamin");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        jLabel15.setFont(new java.awt.Font("Imprint MT Shadow", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Alamat");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel14.setFont(new java.awt.Font("Imprint MT Shadow", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("NIM");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        update.setBackground(new java.awt.Color(196, 218, 210));
        update.setFont(new java.awt.Font("Broadway", 0, 18)); // NOI18N
        update.setForeground(new java.awt.Color(22, 66, 60));
        update.setText("Update");
        update.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel5.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 160, 40));

        jLabel11.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(233, 239, 236));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Output");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 70));
        jPanel5.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 290, 20));

        nama1.setBackground(new java.awt.Color(255, 255, 255));
        nama1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        nama1.setForeground(new java.awt.Color(22, 66, 60));
        nama1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama1ActionPerformed(evt);
            }
        });
        jPanel5.add(nama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 250, -1));

        nim1.setBackground(new java.awt.Color(255, 255, 255));
        nim1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        nim1.setForeground(new java.awt.Color(22, 66, 60));
        nim1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nim1ActionPerformed(evt);
            }
        });
        jPanel5.add(nim1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 250, -1));

        alamat1.setBackground(new java.awt.Color(255, 255, 255));
        alamat1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        alamat1.setForeground(new java.awt.Color(22, 66, 60));
        alamat1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel5.add(alamat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 250, 80));

        JK1.setBackground(new java.awt.Color(106, 156, 137));
        JK1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        JK1.setForeground(new java.awt.Color(0, 0, 0));
        JK1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));
        JK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JK1ActionPerformed(evt);
            }
        });
        jPanel5.add(JK1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 170, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 270, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void risetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_risetActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus semua data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION){
            qw.riset();
            JOptionPane.showMessageDialog(this, "Semua data berhasil dihapus.");
        }
        loadtabel();
    }//GEN-LAST:event_risetActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        String NAMA=nama1.getText();
        String NIM=nim1.getText();
        String ALAMAT=alamat1.getText();
        String GENDER=(String) JK1.getSelectedItem();
        qw.update(NIM, NAMA, ALAMAT, GENDER);
        
        loadtabel();
    }//GEN-LAST:event_updateActionPerformed

    private void KONEKSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KONEKSIActionPerformed
        // TODO add your handling code here:  
    }//GEN-LAST:event_KONEKSIActionPerformed

    private void nimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nimActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
         //delete del=new delete();
        
        int pilihBaris = TABEL.getSelectedRow();
        if (pilihBaris != -1) {
            String NIM=(String) TABEL.getValueAt(pilihBaris, 0);
            
            //hapus ditabel
            //Pilihan hapus = y/n
            int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin ingin dihapus ?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (konfirmasi == JOptionPane.YES_OPTION) {
                //hapus data sesuai NIM untuk dikirim ke JDBC
               
             qw.hapus(NIM);
             loadtabel();
               
            }

        }
        

    }//GEN-LAST:event_hapusActionPerformed

    private void simpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan1ActionPerformed
 
        String NIM=nim.getText();
        String NAMA=nama.getText();
        String ALAMAT=alamat.getText();
        String GENDER=JK.getSelectedItem().toString();
        qw.simpan(NIM, NAMA, ALAMAT, GENDER);
        
        JOptionPane.showMessageDialog(this, "Data berhasil disimpan!", "Success", JOptionPane.INFORMATION_MESSAGE);
        
        //menampilkan
        DefaultTableModel model = (DefaultTableModel) TABEL.getModel();
        model.addRow(new Object[]{nim.getText(), nama.getText(), alamat.getText(), JK.getSelectedItem()});
        
        nim.setText("");
        nama.setText("");
        alamat.setText("");
        JK.setSelectedIndex(0);
    }//GEN-LAST:event_simpan1ActionPerformed

    private void nama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama1ActionPerformed

    private void nim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nim1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nim1ActionPerformed

    private void TABELMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABELMouseClicked
        // TODO add your handling code here:
    int selectedRowIndex = TABEL.getSelectedRow(); //get selected row
    if(selectedRowIndex >=0){
        nim1.setText(TABEL.getValueAt(selectedRowIndex, 0).toString());
        nama1.setText(TABEL.getValueAt(selectedRowIndex, 1).toString());
        alamat1.setText(TABEL.getValueAt(selectedRowIndex, 2).toString());
       //combo box
        String jenisKelamin = TABEL.getValueAt(selectedRowIndex, 3).toString(); // Kolom JK
        JK1.setSelectedItem(jenisKelamin); // Set nilai pada combo box
    }

 
    }//GEN-LAST:event_TABELMouseClicked

    private void JK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JK1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JK1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MahasiswaILKOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MahasiswaILKOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MahasiswaILKOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MahasiswaILKOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MahasiswaILKOM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JK;
    private javax.swing.JComboBox<String> JK1;
    private javax.swing.JTextField KONEKSI;
    private javax.swing.JTable TABEL;
    private javax.swing.JTextField alamat;
    private javax.swing.JTextField alamat1;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nama1;
    private javax.swing.JTextField nim;
    private javax.swing.JTextField nim1;
    private javax.swing.JButton riset;
    private javax.swing.JButton simpan1;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
