/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UAS3;

/**
 *
 * @author Fysl
 */
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import net.proteanit.sql.DbUtils;


public class coba extends javax.swing.JFrame {


    /**
     * Creates new form coba
     */
    query q=new query();
    koneksiJDBC k=new koneksiJDBC();
    public coba() {
        initComponents();
        
        
    }
    
    public void loadtabel() {
        String load = "SELECT * FROM angsuran";
        k.koneksiData();
        try {
            PreparedStatement st = k.conn.prepareStatement(load);
            ResultSet rs = st.executeQuery();
            tabel.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception ex) {
              System.out.println("Gagal coyyy");
        }

    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        motor1 = new javax.swing.JTextField();
        nama1 = new javax.swing.JTextField();
        kontrak1 = new javax.swing.JTextField();
        telepon1 = new javax.swing.JTextField();
        back1 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        cair1 = new javax.swing.JTextField();
        tenor1 = new javax.swing.JComboBox<>();
        simpan1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        status2 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        hapus = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        kontrak = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cair = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tenor = new javax.swing.JComboBox<>();
        motor = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        telepon = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        ubah = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        status = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 222, 77));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Modern No. 20", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("MEGA AUTO FINANCE");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        jLabel16.setFont(new java.awt.Font("Imprint MT Shadow", 0, 28)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Database Rizky");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS3/gmbar/logoR.png"))); // NOI18N
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 150, 100));

        jPanel8.setBackground(new java.awt.Color(243, 254, 184));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 102, 0));
        jLabel18.setText("Motor");
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel19.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 102, 0));
        jLabel19.setText("Nama");
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel20.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 102, 0));
        jLabel20.setText("No. Kontrak");
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel21.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 102, 0));
        jLabel21.setText("No. Tlp");
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        jLabel22.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 102, 0));
        jLabel22.setText("Pencairan");
        jPanel8.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        motor1.setBackground(new java.awt.Color(255, 255, 153));
        motor1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        motor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motor1ActionPerformed(evt);
            }
        });
        jPanel8.add(motor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 180, 30));

        nama1.setBackground(new java.awt.Color(255, 255, 153));
        nama1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.add(nama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 180, 30));

        kontrak1.setBackground(new java.awt.Color(255, 255, 153));
        kontrak1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.add(kontrak1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 180, 30));

        telepon1.setBackground(new java.awt.Color(255, 255, 153));
        telepon1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.add(telepon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 180, 30));

        back1.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        back1.setText("Kembali");
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });
        jPanel8.add(back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 110, 40));

        jLabel23.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 102, 0));
        jLabel23.setText("Tenor");
        jPanel8.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        cair1.setBackground(new java.awt.Color(255, 255, 153));
        cair1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.add(cair1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 180, 30));

        tenor1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36" }));
        jPanel8.add(tenor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 160, 30));

        simpan1.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        simpan1.setText("Simpan");
        simpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan1ActionPerformed(evt);
            }
        });
        jPanel8.add(simpan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 110, 40));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 153));
        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 310, 30));

        jPanel10.setBackground(new java.awt.Color(255, 222, 77));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        status2.setEditable(false);
        status2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel10.add(status2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 476, 340, 40));

        jLabel26.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fysl\\Downloads\\Tanpa judul (3 x 6 inci).png")); // NOI18N
        jPanel10.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 360, -1));

        jLabel27.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fysl\\Downloads\\Tanpa judul (3 x 6 inci) (1).png")); // NOI18N
        jPanel10.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 100));
        jPanel10.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 340, 20));

        jLabel28.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fysl\\Downloads\\Tanpa judul (3 x 6 inci) (2).png")); // NOI18N
        jPanel10.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, 440, 430, 180));

        jLabel29.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fysl\\Downloads\\Tanpa judul (3 x 6 inci) (2).png")); // NOI18N
        jPanel10.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 430, 180));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("utama", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 222, 77));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Modern No. 20", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("MEGA AUTO FINANCE");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Imprint MT Shadow", 0, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Database Rizky");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS3/gmbar/logoR.png"))); // NOI18N
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 150, 100));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fysl\\Downloads\\Tanpa judul (3 x 6 inci) (2).png")); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, -10, 350, 180));

        jPanel4.setBackground(new java.awt.Color(243, 254, 184));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Kontrak", "Nama", "No. Tlp", "Pencairan", "Tenor", "Motor"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 290));

        hapus.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel4.add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 110, 40));

        back.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        back.setText("Kembali");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel4.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 110, 40));

        jPanel5.setBackground(new java.awt.Color(243, 254, 184));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 102, 0));
        jLabel5.setText("No. Kontrak");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        kontrak.setEditable(false);
        kontrak.setBackground(new java.awt.Color(255, 255, 153));
        kontrak.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(kontrak, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 180, 30));

        jLabel10.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 102, 0));
        jLabel10.setText("Pencairan");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        cair.setBackground(new java.awt.Color(255, 255, 153));
        cair.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(cair, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 180, 30));

        jLabel12.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 102, 0));
        jLabel12.setText("Tenor");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, 20));

        tenor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36" }));
        jPanel5.add(tenor, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 160, 30));

        motor.setBackground(new java.awt.Color(255, 255, 153));
        motor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        motor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motorActionPerformed(evt);
            }
        });
        jPanel5.add(motor, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 180, 30));

        jLabel13.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 102, 0));
        jLabel13.setText("Motor");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        jLabel14.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 102, 0));
        jLabel14.setText("No. Tlp");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        telepon.setBackground(new java.awt.Color(255, 255, 153));
        telepon.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(telepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 180, 30));

        jLabel15.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 102, 0));
        jLabel15.setText("Nama");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        nama.setBackground(new java.awt.Color(255, 255, 153));
        nama.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 180, 30));

        ubah.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        ubah.setText("Ubah");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });
        jPanel5.add(ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 90, 40));

        jPanel6.setBackground(new java.awt.Color(255, 222, 77));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        status.setEditable(false);
        status.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel6.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 476, 340, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fysl\\Downloads\\Tanpa judul (3 x 6 inci).png")); // NOI18N
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 360, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fysl\\Downloads\\Tanpa judul (3 x 6 inci) (1).png")); // NOI18N
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 100));
        jPanel6.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 340, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fysl\\Downloads\\Tanpa judul (3 x 6 inci) (2).png")); // NOI18N
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, 440, 430, 180));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fysl\\Downloads\\Tanpa judul (3 x 6 inci) (2).png")); // NOI18N
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 430, 180));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 7, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 8, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("data", jPanel1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 10, 1080, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        int selectedRowIndex = tabel.getSelectedRow(); //get selected row
        if(selectedRowIndex >=0){
            kontrak.setText(tabel.getValueAt(selectedRowIndex, 0).toString());
            nama.setText(tabel.getValueAt(selectedRowIndex, 1).toString());
            telepon.setText(tabel.getValueAt(selectedRowIndex, 2).toString());
            cair.setText(tabel.getValueAt(selectedRowIndex, 3).toString());

            //combo box
            String tnr = tabel.getValueAt(selectedRowIndex, 4).toString(); // Kolom JK
            tenor.setSelectedItem(tnr); // Set nilai pada combo box
            motor.setText(tabel.getValueAt(selectedRowIndex, 5).toString());

        }
    }//GEN-LAST:event_tabelMouseClicked

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        int pilihBaris = tabel.getSelectedRow();
        if (pilihBaris != -1) {
            String nama=(String) tabel.getValueAt(pilihBaris, 0);

            //hapus ditabel
            //Pilihan hapus = y/n
            int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin ingin dihapus ?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (konfirmasi == JOptionPane.YES_OPTION) {
                //hapus data sesuai NIM untuk dikirim ke JDBC
                q.hapus(nama);
            }
            loadtabel();
        }

    }//GEN-LAST:event_hapusActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here
        guiutama u=new guiutama();
        u.setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void motorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motorActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        // TODO add your handling code here:
        String kntrk=kontrak.getText();
        String NAMA=nama.getText();
        String cr=cair.getText();
        String tnr=tenor.getSelectedItem().toString();
        String tlp=telepon.getText();
        String mtr=motor.getText();
        q.update(NAMA, kntrk, tlp, cr, tnr, mtr);

        loadtabel();

    }//GEN-LAST:event_ubahActionPerformed

    private void motor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motor1ActionPerformed

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
        // TODO add your handling code here
        guiutama u=new guiutama();
        u.setVisible(true);
        dispose();
    }//GEN-LAST:event_back1ActionPerformed

    private void simpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan1ActionPerformed
        // TODO add your handling code here:

        String kntrk=kontrak1.getText();
        String NAMA=nama1.getText();
        String cr=cair1.getText();
        String tnr=tenor1.getSelectedItem().toString();
        String tlp=telepon1.getText();
        String mtr=motor1.getText();

        //Peringatan
        if(NAMA.isEmpty() || kntrk.isEmpty() || tlp.isEmpty() || cr.isEmpty() || mtr.isEmpty()){
            JOptionPane.showMessageDialog(this, "Harap Isi yang kosong","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }   else{
            q.simpan(NAMA, kntrk, tlp, cr, tnr, mtr);
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan!", "Success", JOptionPane.INFORMATION_MESSAGE);
        }

        //menampilkan
//        DefaultTableModel model = (DefaultTableModel) tabel.getModel();
//        model.addRow(new Object[]{kntrk,NAMA,tlp,cr,tnr, mtr});

        kontrak.setText("");
        nama.setText("");
        cair.setText("");
        telepon.setText("");
        motor.setText("");
        tenor.setSelectedIndex(0);
        
        
        
        
    }//GEN-LAST:event_simpan1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(coba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(coba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(coba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(coba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new coba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton back1;
    private javax.swing.JTextField cair;
    private javax.swing.JTextField cair1;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField kontrak;
    private javax.swing.JTextField kontrak1;
    private javax.swing.JTextField motor;
    private javax.swing.JTextField motor1;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nama1;
    private javax.swing.JButton simpan1;
    private javax.swing.JTextField status;
    private javax.swing.JTextField status2;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField telepon;
    private javax.swing.JTextField telepon1;
    private javax.swing.JComboBox<String> tenor;
    private javax.swing.JComboBox<String> tenor1;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
}
