/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UAS3;

/**
 *
 * @author Fysl
 */
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import net.proteanit.sql.DbUtils;

public class guiutama extends javax.swing.JFrame {

    /**
     * Creates new form guiutama
     */

    query q=new query();
    koneksiJDBC k=new koneksiJDBC();
    int i=0;
    
    public guiutama() {
        initComponents();
        //Status
        k.koneksiData();
        this.status.setText(k.statuskoneksi);
        this.status1.setText(k.statuskoneksi);
        
        loadtabel();
    }
    
     public void loadtabel() {
        String load = "SELECT * FROM angsuran";
        k.koneksiData();
        try {
            PreparedStatement st = k.conn.prepareStatement(load);
            ResultSet rs = st.executeQuery();
            tabel.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception ex) {
              System.out.println("Gagal coyyy");
        }

    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        input = new javax.swing.JButton();
        daftar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pane = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        motor3 = new javax.swing.JTextField();
        nama3 = new javax.swing.JTextField();
        kontrak3 = new javax.swing.JTextField();
        telepon3 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        cair3 = new javax.swing.JTextField();
        tenor3 = new javax.swing.JComboBox<>();
        simpan3 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        status1 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        hapus = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        kontrak = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cair = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        tenor = new javax.swing.JComboBox<>();
        motor = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        telepon = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        ubah = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        status = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        input.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        input.setText("Input");
        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });
        jPanel1.add(input, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 100, 40));

        daftar.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        daftar.setText("Daftar");
        daftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarActionPerformed(evt);
            }
        });
        jPanel1.add(daftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 100, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS3/gmbar/logoR.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 150, 100));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 240, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fysl\\Downloads\\Tanpa judul (3 x 6 inci) (2).png")); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-210, 290, 410, 180));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fysl\\Downloads\\Tanpa judul (3 x 6 inci) (2).png")); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 320, 310, 180));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fysl\\Downloads\\Tanpa judul (3 x 6 inci) (2).png")); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 200, 410, 180));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fysl\\Downloads\\Tanpa judul (3 x 6 inci) (2).png")); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 310, 180));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 630));

        jPanel13.setBackground(new java.awt.Color(255, 222, 77));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Modern No. 20", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("MEGA AUTO FINANCE");
        jPanel13.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        jLabel40.setFont(new java.awt.Font("Imprint MT Shadow", 0, 28)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setText("Database Rizky");
        jPanel13.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS3/gmbar/logoR.png"))); // NOI18N
        jPanel13.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 150, 100));

        jPanel14.setBackground(new java.awt.Color(243, 254, 184));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(204, 102, 0));
        jLabel42.setText("Motor");
        jPanel14.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel43.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(204, 102, 0));
        jLabel43.setText("Nama");
        jPanel14.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel44.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(204, 102, 0));
        jLabel44.setText("No. Kontrak");
        jPanel14.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel45.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(204, 102, 0));
        jLabel45.setText("No. Tlp");
        jPanel14.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        jLabel46.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(204, 102, 0));
        jLabel46.setText("Pencairan");
        jPanel14.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        motor3.setBackground(new java.awt.Color(255, 255, 153));
        motor3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        motor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motor3ActionPerformed(evt);
            }
        });
        jPanel14.add(motor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 180, 30));

        nama3.setBackground(new java.awt.Color(255, 255, 153));
        nama3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel14.add(nama3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 180, 30));

        kontrak3.setBackground(new java.awt.Color(255, 255, 153));
        kontrak3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel14.add(kontrak3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 180, 30));

        telepon3.setBackground(new java.awt.Color(255, 255, 153));
        telepon3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel14.add(telepon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 180, 30));

        jLabel47.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(204, 102, 0));
        jLabel47.setText("Tenor");
        jPanel14.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        cair3.setBackground(new java.awt.Color(255, 255, 153));
        cair3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel14.add(cair3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 180, 30));

        tenor3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36" }));
        jPanel14.add(tenor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 160, 30));

        simpan3.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        simpan3.setText("Simpan");
        simpan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan3ActionPerformed(evt);
            }
        });
        jPanel14.add(simpan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 110, 40));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(255, 255, 153));
        jTextField3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel14.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 310, 30));

        jPanel15.setBackground(new java.awt.Color(255, 222, 77));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        status1.setEditable(false);
        status1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel15.add(status1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 476, 340, 40));

        jLabel48.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fysl\\Downloads\\Tanpa judul (3 x 6 inci).png")); // NOI18N
        jPanel15.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 360, -1));

        jLabel49.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fysl\\Downloads\\Tanpa judul (3 x 6 inci) (1).png")); // NOI18N
        jPanel15.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 100));
        jPanel15.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 340, 20));

        jLabel50.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fysl\\Downloads\\Tanpa judul (3 x 6 inci) (2).png")); // NOI18N
        jPanel15.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, 440, 430, 180));

        jLabel51.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fysl\\Downloads\\Tanpa judul (3 x 6 inci) (2).png")); // NOI18N
        jPanel15.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 430, 180));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pane.addTab("utama", jPanel4);

        jPanel6.setBackground(new java.awt.Color(255, 222, 77));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Modern No. 20", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("MEGA AUTO FINANCE");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Imprint MT Shadow", 0, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Database Rizky");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS3/gmbar/logoR.png"))); // NOI18N
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 150, 100));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fysl\\Downloads\\Tanpa judul (3 x 6 inci) (2).png")); // NOI18N
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, -10, 350, 180));

        jPanel16.setBackground(new java.awt.Color(243, 254, 184));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Kontrak", "Nama", "No. Tlp", "Pencairan", "Tenor", "Motor"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        jPanel16.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 290));

        hapus.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel16.add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 110, 40));

        back.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        back.setText("Kembali");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel16.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 110, 40));

        jPanel17.setBackground(new java.awt.Color(243, 254, 184));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 102, 0));
        jLabel14.setText("No. Kontrak");
        jPanel17.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        kontrak.setEditable(false);
        kontrak.setBackground(new java.awt.Color(255, 255, 153));
        kontrak.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel17.add(kontrak, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 180, 30));

        jLabel15.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 102, 0));
        jLabel15.setText("Pencairan");
        jPanel17.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        cair.setBackground(new java.awt.Color(255, 255, 153));
        cair.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel17.add(cair, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 180, 30));

        jLabel52.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(204, 102, 0));
        jLabel52.setText("Tenor");
        jPanel17.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, 20));

        tenor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36" }));
        jPanel17.add(tenor, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 160, 30));

        motor.setBackground(new java.awt.Color(255, 255, 153));
        motor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        motor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motorActionPerformed(evt);
            }
        });
        jPanel17.add(motor, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 180, 30));

        jLabel53.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(204, 102, 0));
        jLabel53.setText("Motor");
        jPanel17.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        jLabel54.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(204, 102, 0));
        jLabel54.setText("No. Tlp");
        jPanel17.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        telepon.setBackground(new java.awt.Color(255, 255, 153));
        telepon.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel17.add(telepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 180, 30));

        jLabel55.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(204, 102, 0));
        jLabel55.setText("Nama");
        jPanel17.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        nama.setBackground(new java.awt.Color(255, 255, 153));
        nama.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel17.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 180, 30));

        ubah.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        ubah.setText("Ubah");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });
        jPanel17.add(ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 90, 40));

        jPanel18.setBackground(new java.awt.Color(255, 222, 77));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        status.setEditable(false);
        status.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel18.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 476, 340, 40));

        jLabel56.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fysl\\Downloads\\Tanpa judul (3 x 6 inci).png")); // NOI18N
        jPanel18.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 360, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fysl\\Downloads\\Tanpa judul (3 x 6 inci) (1).png")); // NOI18N
        jPanel18.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 100));
        jPanel18.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 340, 20));

        jLabel57.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fysl\\Downloads\\Tanpa judul (3 x 6 inci) (2).png")); // NOI18N
        jPanel18.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, 440, 430, 180));

        jLabel58.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fysl\\Downloads\\Tanpa judul (3 x 6 inci) (2).png")); // NOI18N
        jPanel18.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 430, 180));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 7, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 8, Short.MAX_VALUE)))
        );

        pane.addTab("data", jPanel5);

        getContentPane().add(pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 1080, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void daftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarActionPerformed
        // TODO add your handling code here
        
        pane.setSelectedIndex(1);
    }//GEN-LAST:event_daftarActionPerformed

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed
        // TODO add your handling code here:
        
        pane.setSelectedIndex(0);
        
    }//GEN-LAST:event_inputActionPerformed

    private void motor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motor3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motor3ActionPerformed

    private void simpan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan3ActionPerformed
        // TODO add your handling code here:

        String kntrk=kontrak3.getText();
        String NAMA=nama3.getText();
        String cr=cair3.getText();
        String tnr=tenor3.getSelectedItem().toString();
        String tlp=telepon3.getText();
        String mtr=motor3.getText();

        //Peringatan
        if(NAMA.isEmpty() || kntrk.isEmpty() || tlp.isEmpty() || cr.isEmpty() || mtr.isEmpty()){
            JOptionPane.showMessageDialog(this, "Harap Isi yang kosong","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }   else{
            q.simpan(NAMA, kntrk, tlp, cr, tnr, mtr);
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan!", "Success", JOptionPane.INFORMATION_MESSAGE);
        }

        //menampilkan
                DefaultTableModel model = (DefaultTableModel) tabel.getModel();
                model.addRow(new Object[]{kntrk,NAMA,tlp,cr,tnr, mtr});

        kontrak3.setText("");
        nama3.setText("");
        cair3.setText("");
        telepon3.setText("");
        motor3.setText("");
        tenor3.setSelectedIndex(0);
        
        pane.setSelectedIndex(1);

    }//GEN-LAST:event_simpan3ActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        int selectedRowIndex = tabel.getSelectedRow(); //get selected row
        if(selectedRowIndex >=0){
            kontrak.setText(tabel.getValueAt(selectedRowIndex, 0).toString());
            nama.setText(tabel.getValueAt(selectedRowIndex, 1).toString());
            telepon.setText(tabel.getValueAt(selectedRowIndex, 2).toString());
            cair.setText(tabel.getValueAt(selectedRowIndex, 3).toString());

            //combo box
            String tnr = tabel.getValueAt(selectedRowIndex, 4).toString(); // Kolom JK
            tenor.setSelectedItem(tnr); // Set nilai pada combo box
            motor.setText(tabel.getValueAt(selectedRowIndex, 5).toString());

        }
    }//GEN-LAST:event_tabelMouseClicked

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        int pilihBaris = tabel.getSelectedRow();
        if (pilihBaris != -1) {
            String nama=(String) tabel.getValueAt(pilihBaris, 0);

            //hapus ditabel
            //Pilihan hapus = y/n
            int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin ingin dihapus ?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (konfirmasi == JOptionPane.YES_OPTION) {
                //hapus data sesuai NIM untuk dikirim ke JDBC
                q.hapus(nama);
            }
            loadtabel();
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here
        pane.setSelectedIndex(0);
    }//GEN-LAST:event_backActionPerformed

    private void motorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motorActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        // TODO add your handling code here:
        String kntrk=kontrak.getText();
        String NAMA=nama.getText();
        String cr=cair.getText();
        String tnr=tenor.getSelectedItem().toString();
        String tlp=telepon.getText();
        String mtr=motor.getText();
        q.update(NAMA, kntrk, tlp, cr, tnr, mtr);

        loadtabel();
    }//GEN-LAST:event_ubahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guiutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guiutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guiutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guiutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guiutama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField cair;
    private javax.swing.JTextField cair3;
    private javax.swing.JButton daftar;
    private javax.swing.JButton hapus;
    private javax.swing.JButton input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField kontrak;
    private javax.swing.JTextField kontrak3;
    private javax.swing.JTextField motor;
    private javax.swing.JTextField motor3;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nama3;
    private javax.swing.JTabbedPane pane;
    private javax.swing.JButton simpan3;
    private javax.swing.JTextField status;
    private javax.swing.JTextField status1;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField telepon;
    private javax.swing.JTextField telepon3;
    private javax.swing.JComboBox<String> tenor;
    private javax.swing.JComboBox<String> tenor3;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
}
